version: '3'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/pizzeria"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"

  db:
    image: 'postgres:14'
    restart: always
    container_name: db
    volumes:
      - /var/lib/postgresql/data/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
#      POSTGRES_HOST: "127.0.0.1"
      POSTGRES_DB: "pizzeria"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432
